{
	"version": 1732936984,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/bag-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/bg-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/buah-sheet0.png",
		"images/buah-sheet1.png",
		"images/buah-sheet2.png",
		"images/buah-sheet3.png",
		"images/desaintanpajudul-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/homeawal-sheet0.png",
		"images/desaintanpajudul3-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/desaintanpajudul4-sheet0.png",
		"images/desaintanpajudul5-sheet0.png",
		"images/buahini-sheet0.png",
		"images/inibuah-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/spritefont.png",
		"images/hewan-sheet0.png",
		"images/hewan-sheet1.png",
		"images/desaintanpajudul6-sheet0.png",
		"images/plusplus-sheet0.png",
		"images/next-sheet0.png",
		"images/goodjob-sheet0.png",
		"images/logosmea-sheet0.png",
		"images/done-sheet0.png",
		"images/desaintanpajudul2-sheet0.png",
		"images/back-sheet0.png",
		"media/game.ogg",
		"media/pou music ost - match tap color tap.m4a",
		"media/pou music ost - match tap color tap.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}